name: Deploy to WordPress.org
on:
  release:
    types: [published]

jobs:
  asset:
    name: Update Asset on WordPress.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: generate
        name: Generate markdown changelog
        uses: LSVH/gha-releases-to-changelog@v1
        with:
          title-template: '### %%TITLE%%'

      - name: Replace placeholders
        uses: LSVH/gha-replace-placeholders@v1
        with:
          include: |
            readme.md
            index.php
          placeholders: |
            %%VERSION%%=${{ steps.generate.outputs.latest }}
            %%CHANGELOG%%=${{ steps.generate.outputs.changelog }}

      - name: Prepare for deployment
        uses: ./.github/actions/prepare-deploy

      - name: Update asset
        uses: 10up/action-wordpress-plugin-asset-update@1.4.1
        env:
          SLUG: ${{ secrets.WPORG_SLUG }}
          SVN_USERNAME: ${{ secrets.WPORG_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WPORG_PASSWORD }}
          README_NAME: readme.md
  plugin:
    name: Deploy Plugin to WordPress.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: generate
        name: Generate markdown changelog
        uses: LSVH/gha-releases-to-changelog@v1
        with:
          title-template: '### %%TITLE%%'

      - name: Replace placeholders
        uses: LSVH/gha-replace-placeholders@v1
        with:
          include: |
            readme.md
            index.php
          placeholders: |
            %%VERSION%%=${{ steps.generate.outputs.latest }}
            %%CHANGELOG%%=${{ steps.generate.outputs.changelog }}

      - name: Prepare for deployment
        uses: ./.github/actions/prepare-deploy

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        uses: php-actions/composer@v5

      - name: Deploy WordPress plugin
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SLUG: ${{ secrets.WPORG_SLUG }}
          SVN_USERNAME: ${{ secrets.WPORG_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WPORG_PASSWORD }}

